/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_RED */
#define LED_RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_0_INBUF_ENABLED 0u
#define LED_RED_0_INIT_DRIVESTATE 1u
#define LED_RED_0_INIT_MUXSEL 0u
#define LED_RED_0_INPUT_SYNC 2u
#define LED_RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_0_NUM 3u
#define LED_RED_0_PORT GPIO_PRT6
#define LED_RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_INBUF_ENABLED 0u
#define LED_RED_INIT_DRIVESTATE 1u
#define LED_RED_INIT_MUXSEL 0u
#define LED_RED_INPUT_SYNC 2u
#define LED_RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_NUM 3u
#define LED_RED_PORT GPIO_PRT6
#define LED_RED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_GREEN */
#define LED_GREEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_0_INBUF_ENABLED 0u
#define LED_GREEN_0_INIT_DRIVESTATE 1u
#define LED_GREEN_0_INIT_MUXSEL 0u
#define LED_GREEN_0_INPUT_SYNC 2u
#define LED_GREEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_0_NUM 1u
#define LED_GREEN_0_PORT GPIO_PRT7
#define LED_GREEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_GREEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_INBUF_ENABLED 0u
#define LED_GREEN_INIT_DRIVESTATE 1u
#define LED_GREEN_INIT_MUXSEL 0u
#define LED_GREEN_INPUT_SYNC 2u
#define LED_GREEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_NUM 1u
#define LED_GREEN_PORT GPIO_PRT7
#define LED_GREEN_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
